services:
  - type: web
    name: coinswag
    runtime: node
    plan: free
    autoDeploy: true
    healthCheckPath: /health
    buildCommand: npm run build
    startCommand: node server-prod.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
