import { Asset } from '../types/asset';

export const TOP_ASSETS: Asset[] = [
  {
    id: 'XMR',
    symbol: 'XMR',
    name: 'Monero (Privacy Hub)',
    chain: 'monero',
    standard: 'native',
    decimals: 12,
    minDeposit: 0.05,
    maxDeposit: 250.0,
    networkFeeAsset: 'XMR',
    estimatedNetworkFee: 0.0001,
    confirmationsRequired: 3,
    isPrivacyHub: true,
    icon: 'https://cryptologos.cc/logos/monero-xmr-logo.svg',
    explorerTxUrl: 'https://localmonero.co/blocks/tx/',
    explorerAddressUrl: 'https://localmonero.co/blocks/search/'
  },
  {
    id: 'BTC',
    symbol: 'BTC',
    name: 'Bitcoin',
    chain: 'bitcoin',
    standard: 'native',
    decimals: 8,
    minDeposit: 0.0005,
    maxDeposit: 5.0,
    networkFeeAsset: 'BTC',
    estimatedNetworkFee: 0.00008,
    confirmationsRequired: 1,
    isPrivacyHub: false,
    icon: 'https://cryptologos.cc/logos/bitcoin-btc-logo.svg',
    explorerTxUrl: 'https://mempool.space/tx/',
    explorerAddressUrl: 'https://mempool.space/address/'
  },
  {
    id: 'ETH',
    symbol: 'ETH',
    name: 'Ethereum',
    chain: 'ethereum',
    standard: 'native',
    decimals: 18,
    minDeposit: 0.01,
    maxDeposit: 50.0,
    networkFeeAsset: 'ETH',
    estimatedNetworkFee: 0.0015,
    confirmationsRequired: 6,
    isPrivacyHub: false,
    icon: 'https://cryptologos.cc/logos/ethereum-eth-logo.svg',
    explorerTxUrl: 'https://etherscan.io/tx/',
    explorerAddressUrl: 'https://etherscan.io/address/'
  },
  {
    id: 'SOL',
    symbol: 'SOL',
    name: 'Solana',
    chain: 'solana',
    standard: 'native',
    decimals: 9,
    minDeposit: 0.1,
    maxDeposit: 500.0,
    networkFeeAsset: 'SOL',
    estimatedNetworkFee: 0.0005,
    confirmationsRequired: 1,
    isPrivacyHub: false,
    icon: 'https://cryptologos.cc/logos/solana-sol-logo.svg',
    explorerTxUrl: 'https://solscan.io/tx/',
    explorerAddressUrl: 'https://solscan.io/account/'
  },
  {
    id: 'USDT-ERC20',
    symbol: 'USDT',
    name: 'Tether USD (ERC20)',
    chain: 'ethereum',
    standard: 'erc20',
    decimals: 6,
    contractAddress: '0xdac17f958d2ee523a2206206994597c13d831ec7',
    minDeposit: 20.0,
    maxDeposit: 100000.0,
    networkFeeAsset: 'ETH',
    estimatedNetworkFee: 0.002,
    confirmationsRequired: 6,
    isPrivacyHub: false,
    icon: 'https://cryptologos.cc/logos/tether-usdt-logo.svg',
    explorerTxUrl: 'https://etherscan.io/tx/',
    explorerAddressUrl: 'https://etherscan.io/address/'
  },
  {
    id: 'USDT-TRC20',
    symbol: 'USDT',
    name: 'Tether USD (TRC20)',
    chain: 'tron',
    standard: 'trc20',
    decimals: 6,
    contractAddress: 'TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t',
    minDeposit: 15.0,
    maxDeposit: 100000.0,
    networkFeeAsset: 'TRX',
    estimatedNetworkFee: 15.0,
    confirmationsRequired: 1,
    isPrivacyHub: false,
    icon: 'https://cryptologos.cc/logos/tether-usdt-logo.svg',
    explorerTxUrl: 'https://tronscan.org/#/transaction/',
    explorerAddressUrl: 'https://tronscan.org/#/address/'
  },
  {
    id: 'USDC-ERC20',
    symbol: 'USDC',
    name: 'USD Coin (ERC20)',
    chain: 'ethereum',
    standard: 'erc20',
    decimals: 6,
    contractAddress: '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48',
    minDeposit: 20.0,
    maxDeposit: 100000.0,
    networkFeeAsset: 'ETH',
    estimatedNetworkFee: 0.002,
    confirmationsRequired: 6,
    isPrivacyHub: false,
    icon: 'https://cryptologos.cc/logos/usd-coin-usdc-logo.svg',
    explorerTxUrl: 'https://etherscan.io/tx/',
    explorerAddressUrl: 'https://etherscan.io/address/'
  },
  {
    id: 'USDC-SPL',
    symbol: 'USDC',
    name: 'USD Coin (Solana SPL)',
    chain: 'solana',
    standard: 'spl',
    decimals: 6,
    contractAddress: 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v',
    minDeposit: 15.0,
    maxDeposit: 100000.0,
    networkFeeAsset: 'SOL',
    estimatedNetworkFee: 0.0005,
    confirmationsRequired: 1,
    isPrivacyHub: false,
    icon: 'https://cryptologos.cc/logos/usd-coin-usdc-logo.svg',
    explorerTxUrl: 'https://solscan.io/tx/',
    explorerAddressUrl: 'https://solscan.io/account/'
  },
  {
    id: 'BNB',
    symbol: 'BNB',
    name: 'BNB (BEP20)',
    chain: 'bsc',
    standard: 'native',
    decimals: 18,
    minDeposit: 0.05,
    maxDeposit: 300.0,
    networkFeeAsset: 'BNB',
    estimatedNetworkFee: 0.0004,
    confirmationsRequired: 15,
    isPrivacyHub: false,
    icon: 'https://cryptologos.cc/logos/bnb-bnb-logo.svg',
    explorerTxUrl: 'https://bscscan.com/tx/',
    explorerAddressUrl: 'https://bscscan.com/address/'
  },
  {
    id: 'XRP',
    symbol: 'XRP',
    name: 'XRP (Ripple)',
    chain: 'ripple',
    standard: 'native',
    decimals: 6,
    minDeposit: 20.0,
    maxDeposit: 50000.0,
    networkFeeAsset: 'XRP',
    estimatedNetworkFee: 0.01,
    confirmationsRequired: 1,
    isPrivacyHub: false,
    icon: 'https://cryptologos.cc/logos/xrp-xrp-logo.svg',
    explorerTxUrl: 'https://xrpscan.com/tx/',
    explorerAddressUrl: 'https://xrpscan.com/account/'
  },
  {
    id: 'LTC',
    symbol: 'LTC',
    name: 'Litecoin',
    chain: 'litecoin',
    standard: 'native',
    decimals: 8,
    minDeposit: 0.1,
    maxDeposit: 1000.0,
    networkFeeAsset: 'LTC',
    estimatedNetworkFee: 0.001,
    confirmationsRequired: 2,
    isPrivacyHub: false,
    icon: 'https://cryptologos.cc/logos/litecoin-ltc-logo.svg',
    explorerTxUrl: 'https://blockchair.com/litecoin/transaction/',
    explorerAddressUrl: 'https://blockchair.com/litecoin/address/'
  },
  {
    id: 'DOGE',
    symbol: 'DOGE',
    name: 'Dogecoin',
    chain: 'dogecoin',
    standard: 'native',
    decimals: 8,
    minDeposit: 50.0,
    maxDeposit: 500000.0,
    networkFeeAsset: 'DOGE',
    estimatedNetworkFee: 1.5,
    confirmationsRequired: 5,
    isPrivacyHub: false,
    icon: 'https://cryptologos.cc/logos/dogecoin-doge-logo.svg',
    explorerTxUrl: 'https://blockchair.com/dogecoin/transaction/',
    explorerAddressUrl: 'https://blockchair.com/dogecoin/address/'
  },
  {
    id: 'AVAX',
    symbol: 'AVAX',
    name: 'Avalanche (C-Chain)',
    chain: 'avalanche',
    standard: 'native',
    decimals: 18,
    minDeposit: 0.2,
    maxDeposit: 1000.0,
    networkFeeAsset: 'AVAX',
    estimatedNetworkFee: 0.005,
    confirmationsRequired: 1,
    isPrivacyHub: false,
    icon: 'https://cryptologos.cc/logos/avalanche-avax-logo.svg',
    explorerTxUrl: 'https://snowtrace.io/tx/',
    explorerAddressUrl: 'https://snowtrace.io/address/'
  },
  {
    id: 'ADA',
    symbol: 'ADA',
    name: 'Cardano',
    chain: 'cardano',
    standard: 'native',
    decimals: 6,
    minDeposit: 20.0,
    maxDeposit: 100000.0,
    networkFeeAsset: 'ADA',
    estimatedNetworkFee: 0.17,
    confirmationsRequired: 10,
    isPrivacyHub: false,
    icon: 'https://cryptologos.cc/logos/cardano-ada-logo.svg',
    explorerTxUrl: 'https://cardanoscan.io/transaction/',
    explorerAddressUrl: 'https://cardanoscan.io/address/'
  },
  {
    id: 'DOT',
    symbol: 'DOT',
    name: 'Polkadot',
    chain: 'polkadot',
    standard: 'native',
    decimals: 10,
    minDeposit: 1.0,
    maxDeposit: 5000.0,
    networkFeeAsset: 'DOT',
    estimatedNetworkFee: 0.015,
    confirmationsRequired: 3,
    isPrivacyHub: false,
    icon: 'https://cryptologos.cc/logos/polkadot-new-dot-logo.svg',
    explorerTxUrl: 'https://polkascan.io/polkadot/transaction/',
    explorerAddressUrl: 'https://polkascan.io/polkadot/account/'
  },
  {
    id: 'POL',
    symbol: 'POL',
    name: 'Polygon',
    chain: 'polygon',
    standard: 'native',
    decimals: 18,
    minDeposit: 15.0,
    maxDeposit: 100000.0,
    networkFeeAsset: 'POL',
    estimatedNetworkFee: 0.01,
    confirmationsRequired: 32,
    isPrivacyHub: false,
    icon: 'https://cryptologos.cc/logos/polygon-matic-logo.svg',
    explorerTxUrl: 'https://polygonscan.com/tx/',
    explorerAddressUrl: 'https://polygonscan.com/address/'
  },
  {
    id: 'LINK',
    symbol: 'LINK',
    name: 'Chainlink (ERC20)',
    chain: 'ethereum',
    standard: 'erc20',
    decimals: 18,
    contractAddress: '0x514910771af9ca656af840dff83e8264ecf986ca',
    minDeposit: 2.0,
    maxDeposit: 5000.0,
    networkFeeAsset: 'ETH',
    estimatedNetworkFee: 0.002,
    confirmationsRequired: 6,
    isPrivacyHub: false,
    icon: 'https://cryptologos.cc/logos/chainlink-link-logo.svg',
    explorerTxUrl: 'https://etherscan.io/tx/',
    explorerAddressUrl: 'https://etherscan.io/address/'
  },
  {
    id: 'ATOM',
    symbol: 'ATOM',
    name: 'Cosmos Hub',
    chain: 'cosmos',
    standard: 'native',
    decimals: 6,
    minDeposit: 1.0,
    maxDeposit: 5000.0,
    networkFeeAsset: 'ATOM',
    estimatedNetworkFee: 0.005,
    confirmationsRequired: 1,
    isPrivacyHub: false,
    icon: 'https://cryptologos.cc/logos/cosmos-atom-logo.svg',
    explorerTxUrl: 'https://atomscan.com/transactions/',
    explorerAddressUrl: 'https://atomscan.com/accounts/'
  },
  {
    id: 'NEAR',
    symbol: 'NEAR',
    name: 'Near Protocol',
    chain: 'near',
    standard: 'native',
    decimals: 24,
    minDeposit: 2.0,
    maxDeposit: 10000.0,
    networkFeeAsset: 'NEAR',
    estimatedNetworkFee: 0.001,
    confirmationsRequired: 1,
    isPrivacyHub: false,
    icon: 'https://cryptologos.cc/logos/near-protocol-near-logo.svg',
    explorerTxUrl: 'https://nearblocks.io/txns/',
    explorerAddressUrl: 'https://nearblocks.io/address/'
  },
  {
    id: 'KAS',
    symbol: 'KAS',
    name: 'Kaspa',
    chain: 'kaspa',
    standard: 'native',
    decimals: 8,
    minDeposit: 50.0,
    maxDeposit: 300000.0,
    networkFeeAsset: 'KAS',
    estimatedNetworkFee: 0.0001,
    confirmationsRequired: 10,
    isPrivacyHub: false,
    icon: 'https://cryptologos.cc/logos/kaspa-kas-logo.svg',
    explorerTxUrl: 'https://explorer.kaspa.org/txs/',
    explorerAddressUrl: 'https://explorer.kaspa.org/addresses/'
  },
  {
    id: 'TON',
    symbol: 'TON',
    name: 'Toncoin',
    chain: 'ton',
    standard: 'native',
    decimals: 9,
    minDeposit: 2.0,
    maxDeposit: 10000.0,
    networkFeeAsset: 'TON',
    estimatedNetworkFee: 0.01,
    confirmationsRequired: 1,
    isPrivacyHub: false,
    icon: 'https://cryptologos.cc/logos/toncoin-ton-logo.svg',
    explorerTxUrl: 'https://tonscan.org/tx/',
    explorerAddressUrl: 'https://tonscan.org/address/'
  },
  {
    id: 'SHIB',
    symbol: 'SHIB',
    name: 'Shiba Inu (ERC20)',
    chain: 'ethereum',
    standard: 'erc20',
    decimals: 18,
    contractAddress: '0x95ad61b0a150d79219dcf64e1e6cc01f0b64c4ce',
    minDeposit: 1000000.0,
    maxDeposit: 5000000000.0,
    networkFeeAsset: 'ETH',
    estimatedNetworkFee: 0.002,
    confirmationsRequired: 6,
    isPrivacyHub: false,
    icon: 'https://cryptologos.cc/logos/shiba-inu-shib-logo.svg',
    explorerTxUrl: 'https://etherscan.io/tx/',
    explorerAddressUrl: 'https://etherscan.io/address/'
  }
];

export const ASSET_MAP: Record<string, Asset> = TOP_ASSETS.reduce((acc, asset) => {
  acc[asset.id] = asset;
  return acc;
}, {} as Record<string, Asset>);
